### ISSUE TITLE
Dockerhub Releases

### ISSUE THREAD

**Issue by DarkRav** [flant/shell-operator#61]
Could you release releases a little more often? The latest tag is updated frequently, but the last release was released 3 months ago.
Thanks

**Comment by distol** [comment]
Hi!

Thank you for your interest in the project.

Unfortunately, we can't do that. We are doing severe refactoring in the master, and we don't feel that releasing untested and not fully completed code would be the right thing to do.

The abovementioned refactoring is almost done, and the last two things we want to do are to change logging to JSON and to add e2e tests. After that, we will release yet another beta, followed (after some time) by the first stable release. The beta should come in a few weeks at max, so it's not too far away.

And of course,  since having in master (and in the latest tag) something that we consider feature-solid, we would highly appreciate any help with testing and documentation.

**Comment by lis0x90** [comment]
Hi, 

Do you have any estimations on next release date?
